FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /home/app
COPY pom.xml .
COPY src ./src
RUN mvn clean package

FROM openjdk:17-jdk-alpine
COPY --from=build /home/app/target/authentication-0.0.1-SNAPSHOT.jar /usr/local/lib/authentication.jar
ENTRYPOINT ["java","-jar","/usr/local/lib/authentication.jar"]